# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config
[profile.default]
optimizer = true
optimizer_runs = 4294967295
via_ir = false
out = "out"
script = "script"
src = "contracts"
test = "test"
